spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1

        ## Service2
        - id: sale-service
          uri: lb://sale-service
          predicates:
            - Path=/sale-service/**
          filters:
            - StripPrefix=1
        
        ## service1
        - id: service-kafka
          uri: lb://service-kafka
          predicates:
            - Path=/service-kafka/**
          filters:
            - StripPrefix=1
            
                
server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka